name: Rust

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --release --all-targets --workspace
      - run: cargo run --release --all-targets --workspace
